server:
  port: 8900
spring:
  application:
    name: gateway
  profiles:
    active: dev
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      discovery:
        locator:
          enabled: false
      routes:
        - id: routeId1
          uri: lb://provider
          predicates:
            - Path=/body/**
        - id: routeId2
          uri: lb://consumer
          predicates:
            - Path=/product/**

