server:
  port: 8900
spring:
  application:
    name: gateway

  profiles:
    default: default
    active: dev
  cloud:

    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
      config:
        server-addr: 127.0.0.1:8848
        file-extension: yaml

    gateway:
      discovery:
        locator:
          enabled: true

    loadbalancer:
      cache:
        enabled: false


