server:
  port: 8901
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    loadbalancer:
      cache:
        enabled: false
    sentinel:
      transport:
        port: 8719
        dashboard: 127.0.0.1:8080
      web-context-unify: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: 123456
    url: jdbc:mysql://121.4.98.178:3306/xxx?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
  application:
    name: consumer
  profiles:
    active: dev

mybatis-plus:
  configuration:
    #生产环境日志sql不打印
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

